# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=27, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=27, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='BinOperationRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField(default=0)),
                ('last_collection', models.DateTimeField(null=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin_app.Bin')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_datetime', models.DateTimeField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin_app.Bin')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='completedoperations',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin_app.Operation'),
        ),
        migrations.AddField(
            model_name='binoperationrel',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin_app.Operation'),
        ),
        migrations.AddField(
            model_name='bin',
            name='operation',
            field=models.ManyToManyField(through='bin_app.BinOperationRel', to='bin_app.Operation'),
        ),
    ]
