# Generated by Django 2.1.4 on 2019-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
